### ISSUE TITLE
Optional auto adding namespace the functions used in the code and reverse_code arguments of RunPython

### ISSUE THREAD

**Issue by luzfcb** [kingbuzzman/django-squash#10]
#### Problem

In a medium complexity project, I have several migrations whose function names referenced in `code` and `reverse_code` of `RunPython` are respectively `forward` and `backward`.
`django-squash` manages to create these functions in the new migration file, however it creates them with duplicate names. As there are more than a hundred of them per app, it is not so good to analyze and correct errors manually.

#### A possible solution

I guess maybe modify `django-squash` instead of using the same name as the original function, change it to generate the function definition name for something like 

```
app_name + _ + migration_file_name_without_extension + _ + function_name + (apps, schema_editor):  # noqa: E501
```

example:
app_name is `user`
migration_file is `0106_populate_foobar_field`
the `code` function is `forward`

```python
def user_0106_populate_foobar_field_forward(apps, schema_editor):  # noqa: E501
    # ....
    # ...
```

Thoughts?

**Comment by kingbuzzman** [comment]
That makes sense, PRs are welcome :D

**Comment by kingbuzzman** [comment]
Inside the [extract_function()](https://github.com/kingbuzzman/django-squash/blob/master/django_squash/management/commands/lib/writer.py#L203), it [gets called here](https://github.com/kingbuzzman/django-squash/blob/master/django_squash/management/commands/lib/writer.py#L221-L223).

Please add an option to turn function renaming on/off. In case someone wants to opt out.

**Comment by kingbuzzman** [comment]
Feel free to reopen this issue if you find any issues.
