### ISSUE TITLE
Touches migrations inside site-packages

### ISSUE THREAD

**Issue by stianjensen** [kingbuzzman/django-squash#12]
This command works great, and is just what I was looking for to workaround shortcomings in the normal sqlashmigrations command.
I was quite surprised to find it tried to squash migrations inside my virtualenv, though. I have a lot of different packages there with migrations, and I also have a lot of self-authored apps, so both `--ignore-app` and `--only` will require a long list of apps (that also needs to be updated over time).
Would it be possible to find some other way to automatically ignore all apps inside site-packages?

**Comment by kingbuzzman** [comment]
This command works as closely to `makemigrations` as can possibly be. Keep in mind there is a settings level variable you can set so you don’t have to run it with `—ignore-app` called `xxx`.

If you have a suggestions, @philfriesen and I are all ears. What we currently have works for us, if you want any changes we will evaluate all PRs presented.

**Comment by stianjensen** [comment]
Thanks! I'll try maintaining a list for ignore_app for now. Will look into creating a PR for excluding all apps in a subdirectory or something :+1:

**Comment by kingbuzzman** [comment]
You can always do:

```
MY_APPS = ['a', 'b', 'c']
DJANGO_APPS = ['da', 'db', 'dc']
THIRD_PARTY_APPS = ['tpa', 'tpb', 'tpc']

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + MY_APPS

DJANGO_SQUASH_IGNORE_APPS = DJANGO_APPS + THIRD_PARTY_APPS
```

_just a suggestion_
