### ISSUE TITLE
`rename_migrations` can fail if migration name does not start with 4 ints

### ISSUE THREAD

**Issue by breid1313** [kingbuzzman/django-squash#14]
we have a migration named like `02_some_name`. probably bad form, but this package should be resilient to that. I can submit a PR to address this shortly.

**Comment by kingbuzzman** [comment]
Hello, and thank you for submitting the pull request.

This matter should be addressed directly with Django. The capability to make such changes is granted by Django itself, and it's not a feature that this library facilitates. Unless this file is causing a bug that affects the generation or reading of migrations, I regret to inform you that this is considered an invalid change.

**Comment by kingbuzzman** [comment]
Legitimate bug, fixed in #18

**Comment by kingbuzzman** [comment]
PR has been merged, version has been bumped. Let me know if this solved it.

**Comment by kingbuzzman** [comment]
@breid1313?

**Comment by kingbuzzman** [comment]
If this becomes an issue again, feel free to reopen it.
