### ISSUE TITLE
NameError: name 'RunPython' is not defined

### ISSUE THREAD

**Issue by harishr1308** [kingbuzzman/django-squash#8]
Hi! I installed the package and squashed my migrations using `python manage.py squash_migrations`.
I'm using Django 3.2.9 and Python 3.9.7
I faced two errors
One was an unexpected indent of @staticmethod function below and the other being RunPython is not defined.

This is the file : /env/lib/python3.9/site-packages/django/contrib/contenttypes/migrations/0003_squashed.py

```
import django.contrib.contenttypes.models
from django.db import migrations, models


@staticmethod
def noop(apps, schema_editor):
    return None


def add_legacy_name(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for ct in ContentType.objects.all():
        try:
            ct.name = apps.get_model(ct.app_label, ct.model)._meta.object_name
        except LookupError:
            ct.name = ct.model
        ct.save()


class Migration(migrations.Migration):

    replaces = [("contenttypes", "0001_initial"), ("contenttypes", "0002_remove_content_type_name")]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100, verbose_name="python model class name")),
            ],
            options={
                "verbose_name": "content type",
                "verbose_name_plural": "content types",
                "db_table": "django_content_type",
                "unique_together": {("app_label", "model")},
            },
            managers=[
                ("objects", django.contrib.contenttypes.models.ContentTypeManager()),
            ],
        ),
        migrations.RunPython(
            code=RunPython.noop,
            reverse_code=add_legacy_name,
            hints={"model_name": "contenttype"},
            elidable=False,
        ),
    ]

```

**Comment by harishr1308** [comment]
The above was resolved by making the below change
```
migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=add_legacy_name,
            hints={"model_name": "contenttype"},
            elidable=False,
        ),
```

**Comment by kingbuzzman** [comment]
The bigger issue i see is that anything inside site packages should be ignored and it decided to squash it.. I’m on vacation now, but i will look into this when i have a chance. thank you for bringing it up to my attention.

**Comment by kingbuzzman** [comment]
@harishr1308 thank you for your patience. I've tried replicating your issue to no avail, if i can ask you to give me a couple of details: 

* where is your code installed?
* why this this [function](https://github.com/kingbuzzman/django-squash/blob/8ff454f594697eecd6a01b8c822b92777fb15674/django_squash/management/commands/lib/loader.py#L23) failing to see the difference between your env (`/env/lib/python3.9/site-packages`) vs where your code is installed in?

**Comment by harishr1308** [comment]
My environment is within the project root directory.

**Comment by kingbuzzman** [comment]
Just to clarify: your code is installed inside the `site-packages` ? i.e. you have a `setup.py` and you ran `install`?

**Comment by kingbuzzman** [comment]
May i ask, why is your dev environment doing inside `site-packages`?

**Comment by kingbuzzman** [comment]
@harishr1308 ?

**Comment by harishr1308** [comment]
Hi! Sorry for getting back to you sooo late. My code is not installed inside site-packages. I've got my local environment sitting on the root of the project directory. This package was installed by running pip install and I configured it as an app in Django Settings and ran python manage.py squashmigrations.

**Comment by kingbuzzman** [comment]
Right, that's an issue. Very few django projects ive seen work this way, and i've personally never worked with one that does.
I can see this working if i create a kind of project variable that holds the apps you want to squash.. or just tell the squash command.

I'll think about it a bit more and get back to you.

**Comment by kingbuzzman** [comment]
Looks like i **did** think ahead. [I included `--only` and `--ignore-apps`](https://github.com/kingbuzzman/django-squash/blob/5402d9dae9e7036ee0ebd3d118e75088319565fd/django_squash/management/commands/squash_migrations.py#L19-L26) arguments to the `squash_migrations` management command. Depending on how many apps you're using, you would chose one or the other, personally, i'd go with `--only` since that would be the most explicit way, but up to you. 

Let me know if that solves your issue.

**Comment by kingbuzzman** [comment]
@harishr1308?

**Comment by harishr1308** [comment]
Hi! I'm sorry but I have since removed the project from my dependencies. We can close this issue as it stands. I'll test it out again with some other personal projects.
